//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTT35.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDONHANG
    {
        public int IDCTDH { get; set; }
        public Nullable<int> IDDH { get; set; }
        public Nullable<int> IDSP { get; set; }
        public Nullable<int> SOLUONGSP { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
