//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTT35.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIACHIKHAC
    {
        public int IDDC { get; set; }
        public Nullable<int> IDND { get; set; }
        public string HOTEN { get; set; }
        public string SDT { get; set; }
        public string DIACHI { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
