//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTT35.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.CTDONHANG = new HashSet<CTDONHANG>();
            this.QLVANCHUYEN = new HashSet<QLVANCHUYEN>();
            this.THANHTOAN = new HashSet<THANHTOAN>();
        }
    
        public int IDDH { get; set; }
        public Nullable<int> IDKM { get; set; }
        public Nullable<int> IDND { get; set; }
        public string HOTEN { get; set; }
        public string DIACHIGIAOHANG { get; set; }
        public string DIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public string GHICHU { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDONHANG> CTDONHANG { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QLVANCHUYEN> QLVANCHUYEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THANHTOAN> THANHTOAN { get; set; }
    }
}
