//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTT35.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIENHE
    {
        public int IDLIENHE { get; set; }
        public string HOTEN { get; set; }
        public string NOIDUNG { get; set; }
        public string EMAIL { get; set; }
    }
}
