//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTT35.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUCGIAOTIEP
    {
        public int IDDANHMUC { get; set; }
        public Nullable<int> IDND { get; set; }
        public Nullable<int> IDTINNHAN { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<System.DateTime> NGAYGUI { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
