//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTT35.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANHOI
    {
        public int IDPHANHOI { get; set; }
        public Nullable<int> IDND { get; set; }
        public Nullable<int> IDSP { get; set; }
        public string HOTENDG { get; set; }
        public string NOIDUNG { get; set; }
        public string CHATLUONGSANPHAM { get; set; }
        public string DUNGVOIMOTA { get; set; }
        public Nullable<double> RATE { get; set; }
        public Nullable<System.DateTime> NGAYPHANHOI { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
