//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTT35.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_PHANBONEntities : DbContext
    {
        public QL_PHANBONEntities()
            : base("name=QL_PHANBONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTDONHANG> CTDONHANG { get; set; }
        public virtual DbSet<DANHMUC> DANHMUC { get; set; }
        public virtual DbSet<DONHANG> DONHANG { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANG { get; set; }
        public virtual DbSet<KHUYENMAI> KHUYENMAI { get; set; }
        public virtual DbSet<MUCGIAOTIEP> MUCGIAOTIEP { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNG { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAP { get; set; }
        public virtual DbSet<PHANHOI> PHANHOI { get; set; }
        public virtual DbSet<QLVANCHUYEN> QLVANCHUYEN { get; set; }
        public virtual DbSet<SANPHAM> SANPHAM { get; set; }
        public virtual DbSet<SANPHAMKHUYENMAI> SANPHAMKHUYENMAI { get; set; }
        public virtual DbSet<THANHTOAN> THANHTOAN { get; set; }
    }
}
