//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTT35.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_PHANBONEntities : DbContext
    {
        public QL_PHANBONEntities()
            : base("name=QL_PHANBONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTDONHANG> CTDONHANG { get; set; }
        public virtual DbSet<DANHMUC> DANHMUC { get; set; }
        public virtual DbSet<DIACHIKHAC> DIACHIKHAC { get; set; }
        public virtual DbSet<DONHANG> DONHANG { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANG { get; set; }
        public virtual DbSet<KHUYENMAI> KHUYENMAI { get; set; }
        public virtual DbSet<LIENHE> LIENHE { get; set; }
        public virtual DbSet<MUCGIAOTIEP> MUCGIAOTIEP { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNG { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAP { get; set; }
        public virtual DbSet<PHANHOI> PHANHOI { get; set; }
        public virtual DbSet<QLVANCHUYEN> QLVANCHUYEN { get; set; }
        public virtual DbSet<SANPHAM> SANPHAM { get; set; }
        public virtual DbSet<SANPHAMKHUYENMAI> SANPHAMKHUYENMAI { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<THANHTOAN> THANHTOAN { get; set; }
    
        [DbFunction("QL_PHANBONEntities", "GetTop10")]
        public virtual IQueryable<GetTop10_Result> GetTop10()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetTop10_Result>("[QL_PHANBONEntities].[GetTop10]()");
        }
    
        [DbFunction("QL_PHANBONEntities", "GetTop10Category")]
        public virtual IQueryable<GetTop10Category_Result> GetTop10Category(Nullable<int> iddm)
        {
            var iddmParameter = iddm.HasValue ?
                new ObjectParameter("iddm", iddm) :
                new ObjectParameter("iddm", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetTop10Category_Result>("[QL_PHANBONEntities].[GetTop10Category](@iddm)", iddmParameter);
        }
    
        [DbFunction("QL_PHANBONEntities", "GetTop10KM")]
        public virtual IQueryable<GetTop10KM_Result> GetTop10KM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetTop10KM_Result>("[QL_PHANBONEntities].[GetTop10KM]()");
        }
    
        [DbFunction("QL_PHANBONEntities", "GetTop30Random")]
        public virtual IQueryable<GetTop30Random_Result> GetTop30Random()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetTop30Random_Result>("[QL_PHANBONEntities].[GetTop30Random]()");
        }
    
        [DbFunction("QL_PHANBONEntities", "LichSuMuaHang")]
        public virtual IQueryable<LichSuMuaHang_Result> LichSuMuaHang(Nullable<int> iDND)
        {
            var iDNDParameter = iDND.HasValue ?
                new ObjectParameter("IDND", iDND) :
                new ObjectParameter("IDND", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<LichSuMuaHang_Result>("[QL_PHANBONEntities].[LichSuMuaHang](@IDND)", iDNDParameter);
        }
    
        [DbFunction("QL_PHANBONEntities", "getDiaChiKhac")]
        public virtual IQueryable<getDiaChiKhac_Result> getDiaChiKhac(Nullable<int> iDND)
        {
            var iDNDParameter = iDND.HasValue ?
                new ObjectParameter("IDND", iDND) :
                new ObjectParameter("IDND", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getDiaChiKhac_Result>("[QL_PHANBONEntities].[getDiaChiKhac](@IDND)", iDNDParameter);
        }
    
        [DbFunction("QL_PHANBONEntities", "getPhanHoiID")]
        public virtual IQueryable<getPhanHoiID_Result> getPhanHoiID(Nullable<int> iDND)
        {
            var iDNDParameter = iDND.HasValue ?
                new ObjectParameter("IDND", iDND) :
                new ObjectParameter("IDND", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getPhanHoiID_Result>("[QL_PHANBONEntities].[getPhanHoiID](@IDND)", iDNDParameter);
        }
    }
}
