//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTT35.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLVANCHUYEN
    {
        public int IDVANCHUYEN { get; set; }
        public Nullable<int> IDDH { get; set; }
        public Nullable<System.DateTime> NGAYVANCHUYEN { get; set; }
        public Nullable<System.DateTime> NGAYGIAOHANG { get; set; }
        public Nullable<decimal> PHIVANCHUYEN { get; set; }
        public string LOAIVANCHUYEN { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
    }
}
