//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTT35.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAMKHUYENMAI
    {
        public int IDSANPHAMKM { get; set; }
        public Nullable<int> IDSP { get; set; }
        public string MAKHUYENMAI { get; set; }
        public string CHITIET { get; set; }
        public Nullable<int> SOLUONGKM { get; set; }
        public Nullable<decimal> GIATIENKM { get; set; }
        public Nullable<System.DateTime> NGAYBD { get; set; }
        public Nullable<System.DateTime> NGAYKT { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
