//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTT35.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTDONHANG = new HashSet<CTDONHANG>();
            this.SANPHAMKHUYENMAI = new HashSet<SANPHAMKHUYENMAI>();
        }
    
        public int IDSP { get; set; }
        public Nullable<int> IDDM { get; set; }
        public Nullable<int> IDNCC { get; set; }
        public string TENSP { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
        public string HINHANH { get; set; }
        public string MOTA { get; set; }
        public string CACHDUNG { get; set; }
        public string NHASANXUAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDONHANG> CTDONHANG { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAMKHUYENMAI> SANPHAMKHUYENMAI { get; set; }
    }
}
