//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTT35.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOAN
    {
        public int IDTHANHTOAN { get; set; }
        public Nullable<int> IDDH { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
        public string HINHTHUCTT { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
    }
}
